import { pgTable, uuid, text, boolean, timestamp, decimal, jsonb, inet, index, integer, uniqueIndex } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

export const adminUsers = pgTable('admin_users', {
  id: uuid('id').defaultRandom().primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash'),
  name: text('name'),
  role: text('role').notNull().default('admin'),
  isActive: boolean('is_active').notNull().default(true),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export const inventory = pgTable('inventory', {
  id: uuid('id').defaultRandom().primaryKey(),
  category: text('category').notNull(),
  title: text('title').notNull(),
  subtitle: text('subtitle'),
  brand: text('brand'),
  brandSlug: text('brand_slug'),
  description: text('description'),
  pricePerDay: decimal('price_per_day', { precision: 10, scale: 2 }),
  pricePerHour: decimal('price_per_hour', { precision: 10, scale: 2 }),
  pricePerWeek: decimal('price_per_week', { precision: 10, scale: 2 }),
  pricePerMonth: decimal('price_per_month', { precision: 10, scale: 2 }),
  pricePer4Hr: decimal('price_per_4hr', { precision: 10, scale: 2 }),
  pricePer6Hr: decimal('price_per_6hr', { precision: 10, scale: 2 }),
  pricePer8Hr: decimal('price_per_8hr', { precision: 10, scale: 2 }),
  currency: text('currency').default('USD'),
  specifications: jsonb('specifications').default(sql`'{}'::jsonb`),
  features: jsonb('features').default(sql`'[]'::jsonb`),
  images: jsonb('images').default(sql`'[]'::jsonb`),
  thumbnails: jsonb('thumbnails').default(sql`'[]'::jsonb`),
  focalPoint: text('focal_point').default('50% 40%'),
  flipHorizontal: boolean('flip_horizontal').notNull().default(false),
  flipVertical: boolean('flip_vertical').notNull().default(false),
  videoUrl: text('video_url'),
  smugmugUrl: text('smugmug_url'),
  imageSourceUrls: jsonb('image_source_urls').default(sql`'[]'::jsonb`),
  isPublished: boolean('is_published').notNull().default(false),
  isFeatured: boolean('is_featured').notNull().default(false),
  availabilityStatus: text('availability_status').notNull().default('available'),
  slug: text('slug').unique(),
  serviceCities: jsonb('service_cities').default(sql`'["miami"]'::jsonb`),
  tags: jsonb('tags').default(sql`'[]'::jsonb`),
  transactionType: text('transaction_type').notNull().default('rental'),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  aiContentGenerated: boolean('ai_content_generated').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  externalSource: text('external_source'),
  externalId: text('external_id'),
  createdBy: uuid('created_by').references(() => adminUsers.id),
  updatedBy: uuid('updated_by').references(() => adminUsers.id),
}, (table) => ({
  categoryIdx: index('idx_inventory_category').on(table.category),
  publishedIdx: index('idx_inventory_published').on(table.isPublished),
  featuredIdx: index('idx_inventory_featured').on(table.isFeatured),
  slugIdx: index('idx_inventory_slug').on(table.slug),
  brandSlugIdx: index('idx_inventory_brand_slug').on(table.brandSlug),
  categoryPublishedFeaturedIdx: index('idx_inventory_cat_pub_feat').on(table.category, table.isPublished, table.isFeatured),
  categoryPublishedIdx: index('idx_inventory_cat_pub').on(table.category, table.isPublished),
  categoryBrandPublishedIdx: index('idx_inventory_cat_brand_pub').on(table.category, table.brandSlug, table.isPublished),
  externalSourceIdIdx: uniqueIndex('idx_inventory_external_source_id').on(table.externalSource, table.externalId),
}))

export const homePageSections = pgTable('home_page_sections', {
  id: uuid('id').defaultRandom().primaryKey(),
  section: text('section').notNull(),
  inventoryId: uuid('inventory_id').references(() => inventory.id, { onDelete: 'cascade' }).notNull(),
  displayOrder: integer('display_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sectionIdx: index('idx_home_page_section').on(table.section),
  orderIdx: index('idx_home_page_order').on(table.section, table.displayOrder),
}))

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id').defaultRandom().primaryKey(),
  tableName: text('table_name').notNull(),
  recordId: uuid('record_id').notNull(),
  action: text('action').notNull(),
  oldValues: jsonb('old_values'),
  newValues: jsonb('new_values'),
  userId: uuid('user_id').references(() => adminUsers.id),
  userEmail: text('user_email'),
  ipAddress: inet('ip_address'),
  userAgent: text('user_agent'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  tableRecordIdx: index('idx_audit_logs_table_record').on(table.tableName, table.recordId),
  createdAtIdx: index('idx_audit_logs_created_at').on(table.createdAt),
}))

export const leadSubmissions = pgTable('lead_submissions', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  email: text('email').notNull(),
  message: text('message'),
  submissionType: text('submission_type').notNull(),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  status: text('status').notNull().default('new'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  typeIdx: index('idx_lead_submissions_type').on(table.submissionType),
  statusIdx: index('idx_lead_submissions_status').on(table.status),
  createdAtIdx: index('idx_lead_submissions_created_at').on(table.createdAt),
}))

export const pricingRules = pgTable('pricing_rules', {
  id: uuid('id').defaultRandom().primaryKey(),
  ruleType: text('rule_type').notNull(),
  category: text('category'),
  minDuration: integer('min_duration'),
  maxDuration: integer('max_duration'),
  discountPercent: decimal('discount_percent', { precision: 5, scale: 2 }),
  isActive: boolean('is_active').notNull().default(true),
  priority: integer('priority').notNull().default(0),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  typeIdx: index('idx_pricing_rules_type').on(table.ruleType),
  categoryIdx: index('idx_pricing_rules_category').on(table.category),
  activeIdx: index('idx_pricing_rules_active').on(table.isActive),
}))

export const addOns = pgTable('add_ons', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  category: text('category').notNull(),
  priceType: text('price_type').notNull(),
  basePrice: decimal('base_price', { precision: 10, scale: 2 }),
  pricePerUnit: decimal('price_per_unit', { precision: 10, scale: 2 }),
  minimumQuantity: integer('minimum_quantity').default(1),
  maximumQuantity: integer('maximum_quantity'),
  unit: text('unit'),
  isActive: boolean('is_active').notNull().default(true),
  displayOrder: integer('display_order').notNull().default(0),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  categoryIdx: index('idx_add_ons_category').on(table.category),
  activeIdx: index('idx_add_ons_active').on(table.isActive),
  orderIdx: index('idx_add_ons_order').on(table.category, table.displayOrder),
}))

export const bundleTemplates = pgTable('bundle_templates', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  displayName: text('display_name').notNull(),
  description: text('description'),
  categories: jsonb('categories').notNull(),
  discountPercent: decimal('discount_percent', { precision: 5, scale: 2 }),
  minimumItems: integer('minimum_items').notNull().default(2),
  isActive: boolean('is_active').notNull().default(true),
  displayOrder: integer('display_order').notNull().default(0),
  icon: text('icon'),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  activeIdx: index('idx_bundle_templates_active').on(table.isActive),
  orderIdx: index('idx_bundle_templates_order').on(table.displayOrder),
}))

export const vendors = pgTable('vendors', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  category: text('category').notNull(),
  description: text('description'),
  contactName: text('contact_name'),
  contactEmail: text('contact_email'),
  contactPhone: text('contact_phone'),
  website: text('website'),
  logo: text('logo'),
  commissionPercent: decimal('commission_percent', { precision: 5, scale: 2 }).default('10.00'),
  customTerms: text('custom_terms'),
  apiType: text('api_type').notNull().default('none'),
  apiCredentials: jsonb('api_credentials').default(sql`'{}'::jsonb`),
  isActive: boolean('is_active').notNull().default(true),
  isFeatured: boolean('is_featured').notNull().default(false),
  displayOrder: integer('display_order').notNull().default(0),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  categoryIdx: index('idx_vendors_category').on(table.category),
  activeIdx: index('idx_vendors_active').on(table.isActive),
  featuredIdx: index('idx_vendors_featured').on(table.isFeatured),
  apiTypeIdx: index('idx_vendors_api_type').on(table.apiType),
}))

export const bookings = pgTable('bookings', {
  id: uuid('id').defaultRandom().primaryKey(),
  bookingNumber: text('booking_number').notNull().unique(),
  customerName: text('customer_name').notNull(),
  customerEmail: text('customer_email').notNull(),
  customerPhone: text('customer_phone').notNull(),
  items: jsonb('items').notNull(),
  addOns: jsonb('add_ons').default(sql`'[]'::jsonb`),
  bundles: jsonb('bundles').default(sql`'[]'::jsonb`),
  baseTotal: decimal('base_total', { precision: 10, scale: 2 }).notNull(),
  discountTotal: decimal('discount_total', { precision: 10, scale: 2 }).default('0.00'),
  addOnsTotal: decimal('add_ons_total', { precision: 10, scale: 2 }).default('0.00'),
  finalTotal: decimal('final_total', { precision: 10, scale: 2 }).notNull(),
  depositAmount: decimal('deposit_amount', { precision: 10, scale: 2 }),
  depositPaid: boolean('deposit_paid').default(false),
  depositPaidAt: timestamp('deposit_paid_at', { withTimezone: true }),
  balanceAmount: decimal('balance_amount', { precision: 10, scale: 2 }),
  balanceDueDate: timestamp('balance_due_date', { withTimezone: true }),
  balancePaid: boolean('balance_paid').default(false),
  balancePaidAt: timestamp('balance_paid_at', { withTimezone: true }),
  securityDeposit: decimal('security_deposit', { precision: 10, scale: 2 }),
  paymentMethod: text('payment_method'),
  status: text('status').notNull().default('pending'),
  startDate: timestamp('start_date', { withTimezone: true }),
  endDate: timestamp('end_date', { withTimezone: true }),
  notes: text('notes'),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  numberIdx: index('idx_bookings_number').on(table.bookingNumber),
  statusIdx: index('idx_bookings_status').on(table.status),
  emailIdx: index('idx_bookings_email').on(table.customerEmail),
  dateIdx: index('idx_bookings_date').on(table.startDate),
}))

export const blogPosts = pgTable('blog_posts', {
  id: uuid('id').defaultRandom().primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  excerpt: text('excerpt'),
  content: text('content').notNull(),
  featuredImage: text('featured_image'),
  category: text('category'),
  tags: jsonb('tags').default(sql`'[]'::jsonb`),
  author: text('author').default('Luxx Miami'),
  isPublished: boolean('is_published').notNull().default(true),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  createdBy: uuid('created_by').references(() => adminUsers.id),
}, (table) => ({
  slugIdx: index('idx_blog_posts_slug').on(table.slug),
  publishedIdx: index('idx_blog_posts_published').on(table.isPublished),
  categoryIdx: index('idx_blog_posts_category').on(table.category),
}))

export const forSaleAssets = pgTable('for_sale_assets', {
  id: uuid('id').defaultRandom().primaryKey(),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull(),
  category: text('category').notNull(),
  brand: text('brand'),
  model: text('model'),
  year: integer('year'),
  heroImage: text('hero_image'),
  images: jsonb('images').default(sql`'[]'::jsonb`),
  imageSourceUrls: jsonb('image_source_urls').default(sql`'[]'::jsonb`),
  advertisedPrice: decimal('advertised_price', { precision: 12, scale: 2 }),
  managedAssetPrice: decimal('managed_asset_price', { precision: 12, scale: 2 }),
  status: text('status').notNull().default('Draft'),
  location: text('location'),
  description: text('description'),
  specifications: jsonb('specifications').default(sql`'{}'::jsonb`),
  badges: jsonb('badges').default(sql`'[]'::jsonb`),
  managementTerms: jsonb('management_terms').default(sql`'{}'::jsonb`),
  documents: jsonb('documents').default(sql`'[]'::jsonb`),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  createdBy: uuid('created_by').references(() => adminUsers.id),
}, (table) => ({
  slugIdx: index('idx_for_sale_assets_slug').on(table.slug),
  categoryIdx: index('idx_for_sale_assets_category').on(table.category),
  statusIdx: index('idx_for_sale_assets_status').on(table.status),
}))

export const carBrands = pgTable('car_brands', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  seoContent: text('seo_content').notNull(),
  logo: text('logo'),
  isPublished: boolean('is_published').notNull().default(true),
  displayOrder: integer('display_order').notNull().default(0),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  slugIdx: index('idx_car_brands_slug').on(table.slug),
  publishedIdx: index('idx_car_brands_published').on(table.isPublished),
}))

export const rolePermissions = pgTable('role_permissions', {
  id: uuid('id').defaultRandom().primaryKey(),
  role: text('role').notNull(),
  section: text('section').notNull(),
  canAccess: boolean('can_access').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  roleIdx: index('idx_role_permissions_role').on(table.role),
  sectionIdx: index('idx_role_permissions_section').on(table.section),
  roleSectionIdx: index('idx_role_permissions_role_section').on(table.role, table.section),
}))

export const callEvents = pgTable('call_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  phoneNumber: text('phone_number').notNull(),
  pageUrl: text('page_url').notNull(),
  pageRoute: text('page_route'),
  deviceType: text('device_type'),
  userAgent: text('user_agent'),
  referrer: text('referrer'),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  createdAtIdx: index('idx_call_events_created_at').on(table.createdAt),
  phoneNumberIdx: index('idx_call_events_phone').on(table.phoneNumber),
  pageRouteIdx: index('idx_call_events_route').on(table.pageRoute),
}))

export const formSubmissionEvents = pgTable('form_submission_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  formType: text('form_type').notNull(),
  pageUrl: text('page_url').notNull(),
  pageRoute: text('page_route'),
  customerName: text('customer_name'),
  customerEmail: text('customer_email'),
  customerPhone: text('customer_phone'),
  payload: jsonb('payload').notNull(),
  deviceType: text('device_type'),
  userAgent: text('user_agent'),
  referrer: text('referrer'),
  metadata: jsonb('metadata').default(sql`'{}'::jsonb`),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  createdAtIdx: index('idx_form_events_created_at').on(table.createdAt),
  formTypeIdx: index('idx_form_events_type').on(table.formType),
  pageRouteIdx: index('idx_form_events_route').on(table.pageRoute),
  emailIdx: index('idx_form_events_email').on(table.customerEmail),
}))

export const uploadLogs = pgTable('upload_logs', {
  id: uuid('id').defaultRandom().primaryKey(),
  fileName: text('file_name').notNull(),
  fileSize: integer('file_size').notNull(),
  fileType: text('file_type'),
  status: text('status').notNull(),
  resultUrl: text('result_url'),
  errorCode: text('error_code'),
  errorMessage: text('error_message'),
  durationMs: integer('duration_ms'),
  uploadContext: text('upload_context'),
  userId: uuid('user_id').references(() => adminUsers.id),
  userEmail: text('user_email'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  createdAtIdx: index('idx_upload_logs_created_at').on(table.createdAt),
  statusIdx: index('idx_upload_logs_status').on(table.status),
  userIdx: index('idx_upload_logs_user').on(table.userId),
}))

export const blockedIps = pgTable('blocked_ips', {
  id: uuid('id').defaultRandom().primaryKey(),
  ipHash: text('ip_hash').notNull().unique(),
  reason: text('reason').notNull(),
  blockedBy: text('blocked_by'),
  isActive: boolean('is_active').notNull().default(true),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  ipHashIdx: index('idx_blocked_ips_hash').on(table.ipHash),
  activeIdx: index('idx_blocked_ips_active').on(table.isActive),
}))

export const rateLimitLog = pgTable('rate_limit_log', {
  id: uuid('id').defaultRandom().primaryKey(),
  ipHash: text('ip_hash').notNull(),
  endpoint: text('endpoint').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  ipHashIdx: index('idx_rate_limit_ip').on(table.ipHash),
  createdAtIdx: index('idx_rate_limit_created').on(table.createdAt),
}))

export const seoPages = pgTable('seo_pages', {
  id: uuid('id').defaultRandom().primaryKey(),
  slug: text('slug').notNull().unique(),
  pageType: text('page_type').notNull(),
  city: text('city').notNull(),
  brand: text('brand'),
  model: text('model'),
  intent: text('intent'),
  category: text('category').notNull().default('car'),
  title: text('title').notNull(),
  h1: text('h1').notNull(),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  content: text('content'),
  contentStatus: text('content_status').notNull().default('pending'),
  isPublished: boolean('is_published').notNull().default(true),
  isIndexable: boolean('is_indexable').notNull().default(true),
  canonicalUrl: text('canonical_url'),
  redirectTo: text('redirect_to'),
  unitCount: integer('unit_count').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  slugIdx: uniqueIndex('idx_seo_pages_slug').on(table.slug),
  pageTypeIdx: index('idx_seo_pages_type').on(table.pageType),
  cityIdx: index('idx_seo_pages_city').on(table.city),
  cityBrandIdx: index('idx_seo_pages_city_brand').on(table.city, table.brand),
  publishedIdx: index('idx_seo_pages_published').on(table.isPublished),
  categoryIdx: index('idx_seo_pages_category').on(table.category),
}))

export const seoPageUnits = pgTable('seo_page_units', {
  id: uuid('id').defaultRandom().primaryKey(),
  seoPageId: uuid('seo_page_id').references(() => seoPages.id, { onDelete: 'cascade' }).notNull(),
  inventoryId: uuid('inventory_id').references(() => inventory.id, { onDelete: 'cascade' }).notNull(),
  isFeatured: boolean('is_featured').notNull().default(false),
  displayOrder: integer('display_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  pageIdx: index('idx_seo_page_units_page').on(table.seoPageId),
  inventoryIdx: index('idx_seo_page_units_inventory').on(table.inventoryId),
  uniquePageUnit: uniqueIndex('idx_seo_page_units_unique').on(table.seoPageId, table.inventoryId),
}))

export const seoIntentMappings = pgTable('seo_intent_mappings', {
  id: uuid('id').defaultRandom().primaryKey(),
  sourceType: text('source_type').notNull(),
  sourceValue: text('source_value').notNull(),
  urlSegment: text('url_segment').notNull(),
  displayName: text('display_name').notNull(),
  category: text('category'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sourceIdx: index('idx_seo_intent_source').on(table.sourceType, table.sourceValue),
  activeIdx: index('idx_seo_intent_active').on(table.isActive),
  categoryIdx: index('idx_seo_intent_category').on(table.category),
}))

export const inventoryDisplaySettings = pgTable('inventory_display_settings', {
  id: uuid('id').defaultRandom().primaryKey(),
  category: text('category').notNull().unique(),
  sortMode: text('sort_mode').notNull().default('featured_first'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  categoryIdx: uniqueIndex('idx_inv_display_settings_category').on(table.category),
}))

export const tourBookings = pgTable('tour_bookings', {
  id: uuid('id').defaultRandom().primaryKey(),
  bookingReference: text('booking_reference').notNull().unique(),
  carId: uuid('car_id').references(() => inventory.id).notNull(),
  routeId: text('route_id').notNull(),
  date: text('date').notNull(),
  startTime: text('start_time').notNull(),
  durationMinutes: integer('duration_minutes').notNull(),
  passengers: integer('passengers').notNull(),
  basePrice: decimal('base_price', { precision: 10, scale: 2 }).notNull(),
  addonPrice: decimal('addon_price', { precision: 10, scale: 2 }).default('0.00'),
  totalPrice: decimal('total_price', { precision: 10, scale: 2 }).notNull(),
  addons: jsonb('addons').default(sql`'[]'::jsonb`),
  status: text('status').notNull().default('pending'),
  holdExpiresAt: timestamp('hold_expires_at', { withTimezone: true }),
  contact: jsonb('contact').notNull(),
  waiverSigned: boolean('waiver_signed').default(false),
  waiverSignedAt: timestamp('waiver_signed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  bookingRefIdx: index('idx_tour_bookings_ref').on(table.bookingReference),
  carDateIdx: index('idx_tour_bookings_car_date').on(table.carId, table.date),
  statusIdx: index('idx_tour_bookings_status').on(table.status),
}))
