-- Add sample car inventory for testing
INSERT INTO inventory (
  id,
  category,
  make,
  model,
  year,
  color,
  price_per_day,
  price_per_hour,
  is_published,
  is_featured,
  slug,
  description,
  images,
  specifications,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'car',
  'Ferrari',
  'SF90 Stradale',
  2024,
  'Rosso Corsa Red',
  2495,
  350,
  true,
  true,
  'ferrari-sf90-stradale',
  'Experience the pinnacle of Ferrari engineering with the SF90 Stradale. This hybrid supercar combines a twin-turbo V8 with electric motors for unprecedented performance.',
  ARRAY['/placeholder.svg?height=600&width=800'],
  '{
    "seats": 2,
    "horsepower": 986,
    "acceleration": "0-60 in 2.5s",
    "transmission": "8-Speed Dual-Clutch",
    "drivetrain": "AWD",
    "fuel_type": "Premium Gasoline + Electric",
    "deposit": "$10,000",
    "mileage_limit": "100 miles/day",
    "features": [
      "Hybrid Powertrain",
      "Carbon Fiber Body",
      "Active Aerodynamics",
      "Racing Seats",
      "Premium Sound System",
      "Navigation System"
    ]
  }'::jsonb,
  now(),
  now()
),
(
  gen_random_uuid(),
  'car',
  'Lamborghini',
  'Huracán',
  2024,
  'Verde Mantis',
  2495,
  325,
  true,
  true,
  'lamborghini-huracan',
  'The Lamborghini Huracán delivers pure Italian supercar excitement with its naturally aspirated V10 engine and razor-sharp handling.',
  ARRAY['/placeholder.svg?height=600&width=800'],
  '{
    "seats": 2,
    "horsepower": 630,
    "acceleration": "0-60 in 3.2s",
    "transmission": "7-Speed Dual-Clutch",
    "drivetrain": "AWD",
    "fuel_type": "Premium Gasoline",
    "deposit": "$8,000",
    "mileage_limit": "100 miles/day",
    "features": [
      "V10 Engine",
      "All-Wheel Drive",
      "Carbon Ceramic Brakes",
      "Sport Seats",
      "Infotainment System",
      "Parking Sensors"
    ]
  }'::jsonb,
  now(),
  now()
),
(
  gen_random_uuid(),
  'car',
  'Rolls-Royce',
  'Cullinan',
  2024,
  'Arctic White',
  1895,
  250,
  true,
  false,
  'rolls-royce-cullinan',
  'The ultimate luxury SUV, the Rolls-Royce Cullinan offers unparalleled comfort and prestige for those who demand the finest.',
  ARRAY['/placeholder.svg?height=600&width=800'],
  '{
    "seats": 5,
    "horsepower": 563,
    "acceleration": "0-60 in 4.8s",
    "transmission": "8-Speed Automatic",
    "drivetrain": "AWD",
    "fuel_type": "Premium Gasoline",
    "deposit": "$5,000",
    "mileage_limit": "150 miles/day",
    "features": [
      "Massage Seats",
      "Starlight Headliner",
      "Champagne Cooler",
      "Rear Entertainment",
      "Air Suspension",
      "Premium Audio"
    ]
  }'::jsonb,
  now(),
  now()
);
